<?php
return [
    'auth' => [
        'query' => [
            'projects' => \Modules\ProjectManagement\App\GraphQL\Queries\Project\GetProjectsQuery::class,
            'project' => \Modules\ProjectManagement\App\GraphQL\Queries\Project\GetProjectByIdQuery::class,
            'projectStats' => \Modules\ProjectManagement\App\GraphQL\Queries\Project\GetProjectStatsQuery::class,
            'userTypes' => \Modules\ProjectManagement\App\GraphQL\Queries\UserTypesQuery::class,
            'projectTypes' => \Modules\ProjectManagement\App\GraphQL\Queries\ProjectTypesQuery::class,
            'workspaceStatus' => \Modules\ProjectManagement\App\GraphQL\Queries\WorkspaceStatusQuery::class,
        ],
        'mutation' => [
            'createProject' => \Modules\ProjectManagement\App\GraphQL\Mutations\CreateProjectMutation::class,
            'updateProject' => \Modules\ProjectManagement\App\GraphQL\Mutations\Project\UpdateProjectMutation::class,
            'deleteProject' => \Modules\ProjectManagement\App\GraphQL\Mutations\Project\DeleteProjectMutation::class,
            'changeProjectStatus' => \Modules\ProjectManagement\App\GraphQL\Mutations\Project\ChangeProjectStatusMutation::class,
            'acceptInvitation' => \Modules\ProjectManagement\App\GraphQL\Mutations\AcceptInvitationMutation::class,
        ],
        'type' => [
            \Modules\ProjectManagement\App\GraphQL\Types\ProjectType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\CreateProjectResponseType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\ProjectInvitationType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\UserTypeType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\ProjectTypeType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\WorkspaceStatusType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\WorkspaceType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Project\ProjectsResponseType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Project\ProjectSingleResponseType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Project\UpdateProjectResponseType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Project\DeleteProjectResponseType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Project\ChangeProjectStatusResponseType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Project\ProjectStatsType::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Task\TaskType::class,
            \Modules\ProjectManagement\App\GraphQL\Inputs\CreateProjectInput::class,
            \Modules\ProjectManagement\App\GraphQL\Inputs\InvitationInput::class,
            \Modules\ProjectManagement\App\GraphQL\Inputs\ProjectInput::class,
            \Modules\ProjectManagement\App\GraphQL\Inputs\ProjectUpdateInput::class,
            \Modules\ProjectManagement\App\GraphQL\Inputs\ProjectFilterInput::class,
            \Modules\ProjectManagement\App\GraphQL\Types\Enums\ProjectStatusEnumType::class,
            \Modules\Core\GraphQL\Types\TranslatableType::class,
            \Modules\Core\GraphQL\Types\TranslatableInputType::class,
            \Modules\Core\GraphQL\Types\User\UserType::class,
            \Modules\Core\GraphQL\Types\UserGroup\UserGroupType::class,
        ]
    ],
];
